version: '2'
services:

  # The MQTT broker service. The mqtt/ directory hosts the Mosca server
  # (currently expected to run on ports 1883 and 3000).
  mqtt:
    build: mqtt
    ports:
      - "1883:1883"
      - "3000:3000"
    depends_on:
      - redis

  # The simulation service. The simulator/ directory hosts the simulator (MQTT
  # client). The following parameters can be used to configure the service.
  simulator:
    build: simulator
    depends_on:
      - mqtt
      #- redis
    environment:
      - BROKER_HOST=mqtt
      #- BROKER_PORT=1883
      - AUTH_USER=simulator
      - AUTH_PASS=secret
      #- TOPICS_START=sensor/start
      #- TOPICS_STOP=sensor/stop
      #- TOPICS_EVENT=sensor/event
      #- TOPICS_ANNOUNCE=sensor/announce
      #- ANNOUNCE_FREQ=5

  # The Redis database used by the server (and possibly the simulator).
  redis:
    build: redis
    expose:
      - "6379"
